### ISSUE TITLE
terminology: manager-agent-client-server

### ISSUE THREAD

**Issue by marcblanchet** [netconf-wg/netconf-over-quic#1]
https://mailarchive.ietf.org/arch/msg/netconf/l-mFI8_3Spta17HzAlv8sEMU-E0/

Kent Watsen: "Section 2 introduces terminology “manager” and “agent” for the NETCONF peers.  I strongly oppose this construct.  Since 2006, the terms “client” and “server” have been used for NETCONF (formally in RFC 6241).  I understand that QUIC also uses the terms “client” and “server”.   To disambiguate, I recommend using "<protocol>-<roll>" everywhere  (like I did in RFC 8071), e.g.: [quic/netconf/tls]-[client/server]."

**Comment by marcblanchet** [comment]
I agree that manager and agent are from SNMP, but no more used in NETCONF.

**Comment by avtobiff** [comment]
Agree.

I found it weird reading about manager and agent in the document.
We should replace it with client/server.
